### ISSUE TITLE
Lisätään pari tietokenttää

### ISSUE THREAD

**Issue by lokori** [solita/avoinkoodi#1]
Taulukossa on nyt kolme kenttää: Omistaja, järjestelmän lyhyt kuvaus ja linkki lähdekoodiin. Järjestelmistä osa on avoimena internetissä ja osalla on myös jonkinlainen "kotisivu", joten sarakkeissa oikeastaan kannattaisi olla myös nämä kaksi lisätietoa.

**Comment by lokori** [comment]
Nyt siellä näkyykin linkit palveluun ja JSON-formaatissa on nämä kentät. Kolmantena asiana voisi olla joku lyhyehkö kuvauskenttä vielä.

Kotisivu-URL ei näy käyttäjälle sikäli kuin sellainen on annettu. Pitää muuttaa layouttia jos sen haluaa, koska taulukko ei toimi suoraan.

**Comment by woltage** [comment]
Fixaako #22 tän?

**Comment by lokori** [comment]
Joo, periaatteessa kyllä. Nyt tietokentät ovat JSON-rakenteessa, mutta kuvauskenttää ei näytetä käyttäjälle kun en vielä keksinyt miten se kannattaisi näyttää.
