### ISSUE TITLE
Avoindata.fi

### ISSUE THREAD

**Issue by Zharktas** [solita/avoinkoodi#12]
Avoindata.fi.n koodit löytyy täältä https://github.com/yhteentoimivuuspalvelut/ytp ja palvelun omistaa Valtori. :p

**Comment by woltage** [comment]
@Zharktas: Haluatko itte täydentää: https://github.com/solita/avoinkoodi/blob/gh-pages/projects.json

**Comment by Zharktas** [comment]
No jos tän kerran, ole hyvä #13 :p
