### ISSUE TITLE
VRK:n kamat

### ISSUE THREAD

**Issue by kakoni** [solita/avoinkoodi#14]
Eli tän alla https://github.com/vrk-kpa
on ainakin
https://github.com/vrk-kpa/xroad-public
https://github.com/vrk-kpa/api-catalog
https://github.com/vrk-kpa/e-identification-proxy-service
https://github.com/vrk-kpa/e-identification-idp-service
https://github.com/vrk-kpa/e-identification-shared-api

**Comment by lokori** [comment]
Olisiko mahdollista saada kuvaus projekteista siten että on jokaisesta ainakin seuraavat tiedot:
1. Lyhyt kuvaus siitä mikä projekti on. 
2. Kuka sen omistaa.
3. Lähdekoodirepositoryn osoite.

Ulkopuolisena on hyvin vaikea hahmottaa mitä eri repositoryissa on pelkän URL:n avulla. 

Ideaalista jos saa suoraan JSON-formaatissa, eli tähän tapaan:
`
        {
            "project": "Sähköisten rakennuslupien lupapiste.fi -palvelu",
            "owner": "Ympäristöministeriö",
            "code_url": "https://github.com/lupapiste/lupapiste",
        "service_url": "https://www.lupapiste.fi/",
        "homepage_url": "-"
    },
`

**Comment by kakoni** [comment]
1. Palveluväylän turvapalvelvin
2. Väestörekisterikeskus
3. https://github.com/vrk-kpa/xroad-public

ja sitten
1. Liityntäkatalogi 
2. Väestörekisterikeskus
3. https://github.com/vrk-kpa/api-catalog

**Comment by lokori** [comment]
Lisätty.
https://github.com/solita/avoinkoodi/pull/21
