### ISSUE TITLE
HSL dev

### ISSUE THREAD

**Issue by kakoni** [solita/avoinkoodi#15]
https://github.com/HSLdevcom

**Comment by lokori** [comment]
Onko siellä jotain selkeitä projekteja, jotka voisi lisätä? Pitäisi saada järjestelmän omistajataho, järjestelmän nimi / lyhyt kuvaus ja koodirepositoryn osoite.

Tämä esimerkiksi? https://github.com/HSLdevcom/digitransit

**Comment by kakoni** [comment]
Joo toi.
1. HSL & Liikennevirasto
2. Digitransit, Uuden ajan matkaopas 
3. https://github.com/HSLdevcom/digitransit

**Comment by lokori** [comment]
Siellä lepää.
