### ISSUE TITLE
Vanhalla Ipadilla ei toimi

### ISSUE THREAD

**Issue by lokori** [solita/avoinkoodi#25]
Tulee joku Javascript-error, eikä näy mitään. iPhonella toimii kyllä ihan hienosti. 

Sivulla on aika vähän Javascriptia, joten ei voi olla montaa koodiriviä joissa voi olla virhe.

**Comment by lokori** [comment]
http://www.html5gamedevs.com/topic/277-possible-fix-for-typeerror-undefined-is-not-a-function-in-html5-games-on-ipad1-safari/

**Comment by lokori** [comment]
https://gist.github.com/jussi-kalliokoski/978329

**Comment by lokori** [comment]
Sivun CSS on myös rikki iPad1 Safarilla. .Sen korjaaminen on vielä oma asiansa.

**Comment by petetnt** [comment]
[`String.prototype.endsWith`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith) (https://github.com/solita/avoinkoodi/blob/gh-pages/js/avoinkoodi.js#L6) ei ole [kovin hyvin tuettu eikä löydy mobiilisafarista ollenkaan ](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith#Browser_compatibility)

**Comment by lokori** [comment]
Kiitos tiedosta! iPadin Safari ei ole kovin ystävällinen kertomaan mikä tarkalleen ottaen on vialla, vaan ulos saa pelkästään tiedon että joku on "undefined".

**Comment by lokori** [comment]
Itse asiassa koko tuo pätkä koodissa on ilmeisesti täysin tarpeetonta kikkailua ja sen voi poistaa kokonaan. Pitää testata iPadilla vielä, mutta luultavasti toimii pienellä siistimisellä.

**Comment by petetnt** [comment]
Juu. Jos sitä tarttee nii `window.location.pathname.slice(-1) === "/"` ajaa saman asian :+1:

**Comment by lokori** [comment]
Erittäin ovela tuo slice-temppukin kyllä :+1: en ajatellut että slicea voisi käyttää noinkin kierosti, mutta Javascript ei olekaan leipälajini. 

Luultavasti tämä korjaa asian ja samalla yksinkertaistaa koodia: 
https://github.com/lokori/avoinkoodi/commit/c4aaf6b302cf4842d564bb58972ff24938388220

Pitää testata kun saan iPadin käsiini.

**Comment by lokori** [comment]
Nyt toimii, kiitos. https://github.com/solita/avoinkoodi/commit/9e1530cbda714306d3dae6cd29117faf3fd79bc6
