### ISSUE TITLE
HTML:n generointi ei escapeta dataa

### ISSUE THREAD

**Issue by komu** [solita/avoinkoodi#27]
Rivillä https://github.com/solita/avoinkoodi/blob/gh-pages/js/avoinkoodi.js#L20 vain katenoidaan raakasti dataa HTML:n keskelle. Kun projektidataan jonain päivänä tulee HTML-erikoismerkkejä, niin tämä aiheuttaa tuhoa.

**Comment by woltage** [comment]
@komu kaikki tietää sun taidot.  See it, fix it ;)

Hyvä pointti, kiitoksia. Korjataan jossain vaiheessa.

**Comment by lokori** [comment]
totta sinänsä.. data tulee staattisesta resurssista eli onhan se "turvallista", mutta jossain vaiheessa gosahtaa tietysti tällä tavalla.

**Comment by komu** [comment]
Jees, kyseessä on nimenomaan layeröintirikos: kukaan ei halua joutua tekemään koko ohjelman dataflow-analyysiä kaikkien muutosten yhteydessä, joten on hyvä pitää vastuut selkeinä.

Mainitaan nyt vielä samassa yhteydessä, että tuossa koodissa `json_url`, `ownerA` ja `ownerB` ovat kaikki globaaleja muuttujia vaikka niiden olisi varmasti tarkoitus olla lokaaleja. Kannattaa kirjoittaa kaikki koodinsa strict-modessa niin tällaiset jäävät kiinni. On myös ihan hyvä ajatus konffata työkalunsa huutamaan siitä jos unohtaa käyttää strict modea.

**Comment by lokori** [comment]
Onhan se hyvä ajatus :) Nyt on strict modekin.
https://github.com/solita/avoinkoodi/commit/cbbcda002c3aeeb7dffd958513286f493f93d19c
