### ISSUE TITLE
Some-buttonit

### ISSUE THREAD

**Issue by villepaivinen** [solita/avoinkoodi#37]
Twitter, facebook, g+ -napukat etusivulle

**Comment by lokori** [comment]
Jotain tällaista siis:
 https://developers.facebook.com/docs/plugins/like-button#example
https://about.twitter.com/resources/buttons

**Comment by jkumara** [comment]
Pitäiskö laittaa samanlaiset kun noissa Solita.fi:n artikkeleissa? http://www.solita.fi/think-tank/julkishallinnon-toimintatavat-uudistettava-pintaa-syvemmalta/ Pitää vaan lisätä og-tagit tälle sivulle.

**Comment by lokori** [comment]
Sanoisin että ei tehdä noin vaan noudatetaan ohjetta. Ei ole Twitterin ja Facebookin mielestä asiallista brändätä niitä nappuloita uudelleen joka saitilla.

**Comment by jkumara** [comment]
Hyvä pointti, mennään defaulteilla.
